### ISSUE TITLE
Define assignable values on class

### ISSUE THREAD

**Issue by codener** [makandra/assignable_values#11]
Although assignable_values can return different value sets for each record, a very common use case are static assignable values. Many times I've tried to query the class for them, but I had to instantiate a new Record just to ask for the static assignable values.

``` ruby
Car.assignable_brands # => not defined
Car.new.assignable_brands # => returns brands
```

It would be nice if I could decide whether I want to define the assignable values on class or instance level. A definition on class level would then mean that the assignable values are the same for all instances.

``` ruby
class Car
  self.assignable_values_for(:brands) { %[audi bmw mercedes porsche])
end
```

What do you think about this?

**Comment by henning-koch** [comment]
We had this feature in an early draft of the code, but it made the logic become convoluted and hard to reason about. We ended up removing it for that reason.

**Comment by henning-koch** [comment]
Closing stale issue.
