### ISSUE TITLE
Assignable values change from 0.11.1 to 0.11.2

### ISSUE THREAD

**Issue by tiagotex** [makandra/assignable_values#13]
I have updated the gem from 0.11.1 to 0.11.2 and my tests started breaking. In the controller we define:

```ruby
assignable_values_for :variable, allow_blank: true do
    ['one', 'two', 'three']
end
```

When calling `assignable_variables` this are the results.

v0.11.1:
```ruby
[ 'one', 'two', 'three']
```

v0.11.2:
```ruby
[nil, 'one', 'two', 'three']
```

Was this change on propose? I couldn't find a changelog.

**Comment by tiagotex** [comment]
This causes another problem, in the view I do:

```ruby
= f.input :variable, as: :select, collection: f.object.humanized_variables.map { |av| [av.humanized, av.value] }.sort
```

This breaks because `f.object.humanized_variables` returns:

```ruby
[
#<AssignableValues::HumanizedValue value: nil, humanized: nil>,
#<AssignableValues::HumanizedValue value: "one", humanized: "One">,
#<AssignableValues::HumanizedValue value: "two", humanized: "Two">],
#<AssignableValues::HumanizedValue value: "three", humanized: "Three">
]
```

**Comment by henning-koch** [comment]
I don't think this behavior was changed between 0.11.1 and 0.11.2. Nevertheless, starting with 0.12.0 `assignable_values` and `humanized_values` will no longer include a previously saved value if that value is blank.
