### ISSUE TITLE
Version 0.12 is broken

### ISSUE THREAD

**Issue by tiagotex** [makandra/assignable_values#14]
In version 0.12 of this gem, Gemika was added to check the version of active_record used, but it wasn't added to the list of dependencies so it breaks when adding this gem to projects without Gemika.

```ruby
assignable_values-0.12.0/lib/assignable_values/active_record/restriction/base.rb:167:
in `ensure_after_initialize_callback_enabled': uninitialized constant AssignableValues::ActiveRecord::Restriction::Base::Gemika (NameError)
```

As far as I understood, Gemika is a development dependency and it shouldn't be required.

@henning-koch Let me know if you need some more information or if I misunderstood something. Thank you

**Comment by henning-koch** [comment]
That was a bad oversight on my part, sorry.

We removed the runtime dependency on gemika in 0.12.1.
