### ISSUE TITLE
Add support for Array columns

### ISSUE THREAD

**Issue by codener** [makandra/assignable_values#19]
It would be nice if one could use `assignable_values` for controlling `array` fields that e.g. PostgreSQL offers. The semantics for such a field would be different from scalar fields:

- validation would check whether the field is a subset of the specified assignable values
- inclusion of previous values would use union
- maybe more

I might build a PR.

**Comment by triskweline** [comment]
If you want to tackle this, you probably need to refactor the class hierarchy like this:

```
Restriction::Base
|
+-- Restriction::SingleValue (currently Restriction::Base)
|   |
|   +--- Restriction::SimpleAttribute (currently Restriction::ScalarAttribute)
|   |
|   +--- Restriction::BelongsToAssociation
|
+-- Restriction::MultipleValues
    |
    +--- Restriction::ArrayAttribute
```

**Comment by triskweline** [comment]
@kratob @codener Can you come up with a few real-world examples for models with array fields that would benefit from this? Tags maybe?

**Comment by kratob** [comment]
I've recently encountered an authorization logic where users could have multiple roles; that might have been a valid use case.

**Comment by triskweline** [comment]
Maybe a app where a 1-to-n association is migrated to a n-to-n, and the developer does not want to use a join model?

**Comment by codener** [comment]
I believe the correct term for this feature would would be "multiple select". E.g. by passing a `multiple: true` option, the assignable values list would become a pool of values, of which any subset would be valid.

I believe a list of selectable tags was the trigger for this feature request. In the meantime, I've also had lists of allowed features, e.g. allowed rendering styles for an element that should be validated, or social media profiles to choose.

**Comment by kratob** [comment]
In 0.14.0.

**Comment by kratob** [comment]
There is still an issue:
We used to define methods `#humanized_value` (returning the humanization of the current value) and `#humanized_values` (returning the humanizations of all possible values). In the array case, where fields are usually pluralized to begin with, this will always return the second variant, which is confusing.

**Comment by kratob** [comment]
I.e.
```
$ record.colors  # ['red', 'green']
$ record.humanized_colors.map(&:to_s)  # ['Red', 'Green', 'Blue', 'Yellow']
```

I'm not quite sure what the best fix is. Maybe introduce `#all_humanized_colors` to returns all possible values, keep supporting the current behavior for the non-array case, and then use `#humanized_colors` and `#all_humanized_colors` for the array case, even if this is a breaking change?

_Note_: As a workaround, `record.colors.map(&:humanize)` will work as well.

**Comment by kratob** [comment]
(@denzelem)

**Comment by triskweline** [comment]
> Note: As a workaround, record.colors.map(&:humanize) will work as well.

But does this respect I18n entries as `#humanized_value` would? `String#humanize` is only a fallback.

**Comment by kratob** [comment]
You're right, it probably does not work as I thought it would.

**Comment by triskweline** [comment]
In hindsight I kind of hate how `#humanized_foo` and `#humanized_foos` look so similiar, even though they return completely different types of things.

Maybe we can argue that the two methods should pertain to a single value of an array field like this:

```
humanized_color(given_color) # only works with a given value and raises without arg
humanized_colors # returns all value/humanized tuples for a single array value
```

**Comment by denzelem** [comment]
Another suggestion in comparison to the `all_*` approach. 

```
-- string column
#humanized_color
#humanized_colors

-- array column
#humanized_colors(multiple: :selected) 
#humanized_colors(multiple: :available)
```

The `humanized_colors` method should raise an `ArgumentError` if it is an array column an no `multiple` argument key is given. And it should raise, if a `multiple` argument is given, but it is just an string column.

**Comment by kratob** [comment]
We'll go with this:

Singular

```
humanized_color                      # String
humanized_color(other_value)         # String
humanized_colors                     # Array[HumanizedValue] of all values, deprecated
assignable_colors                    # Array[HumanizableString], deprecated (in HumanizableString#humanized)
all_humanized_colors                 # Array[HumanizedValue] of all values
```

Plural

```
humanized_colors                     # Array[String] of current values
humanized_color(other_value)         # String
assignable_colors                    # Array[HumanizableString] of all values, deprecated (in HumanizableString#humanized)
all_humanized_colors                 # Array[HumanizedValue] of all values
```

**Comment by triskweline** [comment]
I would flip the adjectives:

`assignable_humanized_colors` => `humanized_assignable_colors`.

This breaks my brain less, since `humanized_assignable_colors` builds upon `assignable_colors`.

**Comment by kratob** [comment]
Released as 0.15.0.

**Comment by codener** [comment]
Awesome, thanks!

**Comment by denzelem** [comment]
I upgraded to 0.15.0, but I'm missing the method to received all current values of an array attribute. The method should be named `humanized_colors`, but I only have theses methods available:

```
[
  :assignable_colors,
  :colors,
  :colors=,
  :colors?,
  :colors_before_last_save,
  :colors_before_type_cast,
  :colors_came_from_user?,
  :colors_change,
  :colors_change_to_be_saved,
  :colors_changed?,
  :colors_in_database,
  :colors_previous_change,
  :colors_previously_changed?,
  :colors_was,
  :colors_will_change!,
  :humanized_assignable_colors,
  :humanized_color,
  :restore_colors!,
  :saved_change_to_colors,
  :saved_change_to_colors?,
  :validate_colors_assignable,
  :will_save_change_to_colors?,
]
```

The model looks similar to this:

```
class Foo < ApplicationRecord
  assignable_values_for :colors, allow_blank: true, multiple: true do
    ['target_groups']
  end
end
```

**Comment by kratob** [comment]
You're right. Should work in 0.15.1.

**Comment by denzelem** [comment]
Thanks!
