### ISSUE TITLE
#humanized_assignable_<value>s is not supporting option :include_old_value

### ISSUE THREAD

**Issue by NatalieKrehan** [makandra/assignable_values#26]
Since `#assignable_<value>.humanized` is deprecated I would like `#humanized_assignable_<value>s` to support option `:include_old_value` as the documentation suggests for excluding those values that are not actually intended to be assignable

**Comment by kratob** [comment]
This feature was supposedly added in 0.16.1. Did you try on that version?

**Comment by NatalieKrehan** [comment]
your are right. My fault. Update to 0.16.1 fixed it. Thanks!
