### ISSUE TITLE
Loads all assignable records of belongs_to association into an array

### ISSUE THREAD

**Issue by foobear** [makandra/assignable_values#27]
When using `assignable_values` with a `belongs_to` association, it loads all records from the given scope when validating the assigned value.

Example:
```ruby
class Contract
  belongs_to :customer
  assignable_values_for(:customer) { Customer.active }
end

class Customer
  scope :active, -> { where(trashed: false) }
end
```

```ruby
my_customer = Customer.create!
# INSERT INTO customers ...
Contract.create!(customer: my_customer)
# SELECT "customers".* FROM "customers" WHERE "customers"."trashed" = FALSE
# INSERT INTO contracts ...
```

I did not dig too deep, but the culprit might be `assignable_values_from_record_or_delegate` calling `to_a`:
https://github.com/makandra/assignable_values/blob/master/lib/assignable_values/active_record/restriction/base.rb#L218-L224

However, changing that behavior might not be enough as calling `include?` on a relation also creates an array of records. So we probably need to keep scopes as scopes, but also do a check like

```ruby
scope.where(association_id_method => association_id(record)).exists?
```

I'm on Rails 6 but assume this is an issue in older versions as well.

**Comment by kratob** [comment]
Proposed fix:
When validating:
- First check if the value equals the old value. If so, validation is okay.
- If not, use the scope and use `#exists?`. To get the scope, check if we can call `to_a` as late as possible, or not explicitly call it at all.
