### ISSUE TITLE
raise an ArgumentError if unsupported options are passed

### ISSUE THREAD

**Issue by makmic** [makandra/assignable_values#43]
Hi :wave: 

I was recently debugging code that looked roughly like this:

```rb
authorize_values_for :user_ids, if: :state_ready?
```

it took me quite some time that it made the wrong assumption that assignable_values supports an `if` option. This brings me to two feature requests:

* `authorize_values_for` and `assignable_values_for` should raise an `ArgumentError` if any option passed to these functions are unknown
* `if` and `unless` could be supported :-)

**Comment by mak-dunkelziffer** [comment]
- I added error messages for unsupported options to `assignable_values_for`.
- The method `authorize_values_for` is from consul and just passes its options into `asssignable_values_for`, so you will get that error message there as well.
- We currently have no plans to support `if` and `unless`.

**Comment by makmic** [comment]
Hi @mak-dunkelziffer,
thank you for the patch! Very much appreciated :-)
