### ISSUE TITLE
Documentation Request: Is Rails 7.x supported?

### ISSUE THREAD

**Issue by brandonzylstra** [makandra/assignable_values#46]
Several things in the repo were updated last week, so I would assume that this project is updated to work with Rails 7.x, and files like [Gemfile.7.0.pg](https://github.com/makandra/assignable_values/blob/master/Gemfile.7.0.pg) would seem to support that inference, but then I see this in the README and I'm not so sure:

> `assignable_values` is tested with Rails 5.1 and 6.1 on Ruby 2.5, 2.7 and 3.0.

Can you clarify?

**Comment by brandondrew** [comment]
Additionally, can we expect it to work with Ruby 3.3, 3.2, and 3.1?

**Comment by jakobscholz** [comment]
> Additionally, can we expect it to work with Ruby 3.3, 3.2, and 3.1?

Hi Brandon, thanks for the issue! The gem is now tested against ruby 3.3 and 7.1.
