### ISSUE TITLE
Add support for Rails store accessor attributes

### ISSUE THREAD

**Issue by brunosedler** [makandra/assignable_values#48]
It would be nice, if `assignable_values` would fully support [Rails store accessor attributes](https://api.rubyonrails.org/classes/ActiveRecord/Store.html). They have been around for quite a while now, and and are mostly quite pleasant to work with. If `assignable_values` would also support them, it would further enhance the usage of them. 

Most of the `assignable_values`  functionality already seems to work fine enough for store accessor attributes out of the box, but I came across at least one issue. The `allow_blank` option does  not work for store accessor attributes on update. I assume, this has to do with the feature of always allowing the value that's already saved in the database and the [check for the value in the database](https://github.com/makandra/assignable_values/blob/2d4c2909d8848233794ef03e0c864a8bac74eff5/lib/assignable_values/active_record/restriction/scalar_attribute.rb#L109), that is performed to achieve this. 

Now, since store attributes do not have an own database column, this check will always return `nil` and therefore always allow `nil`-values when validating the attribute.  

As store attribute are its own kind of attribute (like `belongs_to` relations), they should probably be handled in an own restriction class, like `AssignableValues::ActiveRecord::Restriction::StoreAttribute` to explicitly handle all peculiarities of store attributes.

**Comment by begerdom** [comment]
Implemented in #50
