### ISSUE TITLE
Feature: Support symbol->value mapping for scalar values / integer columns

### ISSUE THREAD

**Issue by ahacking** [makandra/assignable_values#5]
I find this gem and its Consul companion gem quite interesting, however I cannot use it currently because I need to support integer columns and readable code. I would like to be able to use a symbol to value mapping for integer columns as can be done with the enumerize gem.

eg something like:

```
assignable_values_for :genre, mapping: -> { { pop: 1, :jazz: 2, rock: 3 } } do
 genres = []
 genres << :pop  # symbol
 genres << 'jazz' if year > 1900  # string/indifferent mapping
 genres << 3 if year > 1960 # specify value for :rock
 genres
end
```

The idea being the i18n lookup uses the hash key (ie the symbol), and the column gets the mapped value.

Some of the other enumerize features:

```
song.genre = :pop
song.genre.pop?
Song.with_genre(:pop, :rock)
Song.without_genre(:jazz)
```

Any thoughts you may have on implementing/integrating integer column support and some of the enumerize features would be grateful.

**Comment by triskweline** [comment]
Closing stale issue.
